### ISSUE TITLE
Can't see any data in Grafana

### ISSUE THREAD

**Issue by torblerone** [chaos-mesh/chaos-mesh-datasource#30]
Hello, first of all BIG thanks to you for making your ChaosMesh observable through Grafana!

I added the Datasource according to the tutorial and Grafana accepted and saved it. But when I try to add the first panel, it looks like Grafana isn't able to fetch any data from it. I can't even choose a namespace. See below picture.

Do you have any tips to debug this? Maybe I'm just missing something.

![grafik](https://user-images.githubusercontent.com/64590448/105463967-1d81ef00-5c91-11eb-9318-c84ccbb5b3ba.png)

**Comment by g1eny0ung** [comment]
It seems to be an API URL configuration problem.

For example, in my local machine, I have already port-forward a chaos mesh service by `kubectl port-forward -n chaos-testing svc/chaos-dashboard 2333:2333`, so I need to fill the `http://localhost:2333` as below screenshot:

![image](https://user-images.githubusercontent.com/15034155/106103155-73680280-617b-11eb-8c3c-28ce3fb3c235.png)

And also, for the current implementation, whether it is installed via `helm` or `install.sh`, you need to configure the `timezone` to fit your browser timezone 😢.

Like: `helm install chaos-mesh helm/chaos-mesh --namespace=chaos-testing --set dashboard.create=true,dashboard.securityMode=false,timezone=Asia/Shanghai`

This is a bug, the problem is even you choose a different timezone in the Grafana time range, it still keeps in the browser timezone.

I will plan to rewrite the datasource plugin to prevent these problems. In fact, there is no need to manually set the timezone when install, because the server can uniformly convert different time zones into UTC time for processing.

**Comment by yeya24** [comment]
Thanks @g1eny0ung for the answer! I think he already covered all cases. 

@torblerone  For the URL, when you configured the data source, the URL you entered should be correct, otherwise there will be some error saying the data source is wrong.

Btw It would be great to support timezone converting!

**Comment by zhuwenxing** [comment]
get a same issue

![image](https://user-images.githubusercontent.com/12268675/110323451-97a6e100-804f-11eb-9bf9-9db1e5cc4c3e.png)

**Comment by g1eny0ung** [comment]
@zhuwenxing I'm already rewriting the data source plugin in https://github.com/g1eny0ung/grafana-chaos-mesh-datasource. This plugin fixes a few issues and supports the feature of **variables**.

Currently, it's still in the [grafana plugin repository pipeline](https://github.com/grafana/grafana-plugin-repository/pull/879). Before it publishes, you can go to the [releases](https://github.com/g1eny0ung/grafana-chaos-mesh-datasource/releases) to download the production zip and have a try.

If you find some problems after trying, welcome to our slack channel (#project-chaos-mesh) to discuss with us, or you can also open an issue to the repo to describe your problem.

**Comment by yeya24** [comment]
@g1eny0ung Any plan to move your plugin to this repo?

**Comment by g1eny0ung** [comment]
> @g1eny0ung Any plan to move your plugin to this repo?

I once thought about overwriting the files in this repo to make changes, but because there are many changes, I chose to push to my own repo first.

If I choose, I prefer to archive this repo? This can prevent some problems, like version conflicts, etc.

**Comment by zhuwenxing** [comment]
> @zhuwenxing I'm already rewriting the data source plugin in https://github.com/g1eny0ung/grafana-chaos-mesh-datasource. This plugin fixes a few issues and supports the feature of **variables**.
> 
> Currently, it's still in the [grafana plugin repository pipeline](https://github.com/grafana/grafana-plugin-repository/pull/879). Before it publishes, you can go to the [releases](https://github.com/g1eny0ung/grafana-chaos-mesh-datasource/releases) to download the production zip and have a try.
> 
> If you find some problems after trying, welcome to our slack channel (#project-chaos-mesh) to discuss with us, or you can also open an issue to the repo to describe your problem.

sure,  I will try it later!

**Comment by g1eny0ung** [comment]
> > @g1eny0ung Any plan to move your plugin to this repo?
> 
> I once thought about overwriting the files in this repo to make changes, but because there are many changes, I chose to push to my own repo first.
> 
> If I choose, I prefer to archive this repo? This can prevent some problems, like version conflicts, etc.

After discussion with @yeya24, we have already moved the new implementation into this repo.

**Comment by g1eny0ung** [comment]
Close due to the new datasource plugin finally being published. (Note that the latest plugin is only available for Chaos Mesh version 1.x. We will continue to update it to support 2.0)
